### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by alex27riva** [dr-mod/zero-btc-screen#13]
Hi, it hasn't worked for a few days anymore, I get this error:

```
Traceback (most recent call last):
  File "/home/pi/zero-btc-screen/main.py", line 61, in <module>
    main()
  File "/home/pi/zero-btc-screen/main.py", line 47, in main
    data_sink.update_observers(prices)
  File "/home/pi/zero-btc-screen/presentation/observer.py", line 18, in update_observers
    observer.update(data)
  File "/home/pi/zero-btc-screen/presentation/screens/epd2in13v2.py", line 54, in update
    self.form_image(data, self.screen_draw)
  File "/home/pi/zero-btc-screen/presentation/screens/epd2in13v2.py", line 41, in form_image
    Plot.candle(prices, size=(SCREEN_WIDTH - 45, 93), position=(41, 0), draw=screen_draw)
  File "/home/pi/zero-btc-screen/data/plot.py", line 63, in candle
    open = window[0][0]
IndexError: list index out of range
```

**Comment by dr-mod** [comment]
Hi @alex27riva, could you provide with any more details / configuration please?
I've got 2 of them running, but haven't encountered this error.

**Comment by alex27riva** [comment]
Now is working fine, maybe there was a momentary problem with the Coindesk API.
