### ISSUE TITLE
Getting an error when trying to run main.py

### ISSUE THREAD

**Issue by jared7118** [dr-mod/zero-btc-screen#36]
Hi, I have set this up with a pi zero w with a Waveshare 2.13 inch SPI E-Ink E-Paper (B) Display - 3 Colors; followed the instructions to a T, but I am getting the following:

jared7118@raspberrypi:~ $ python3 ~/zero-btc-screen/main.py
Traceback (most recent call last):
  File "/home/jared7118/zero-btc-screen/main.py", line 60, in <module>
    main()
  File "/home/jared7118/zero-btc-screen/main.py", line 40, in main
    builder.bind(data_sink)
  File "/home/jared7118/zero-btc-screen/config/builder.py", line 23, in bind
    screen_class(observable=observable, **kwargs)
  File "/home/jared7118/zero-btc-screen/presentation/screens/epd2in13v2.py", line 23, in __init__
    self.epd = self._init_display()
  File "/home/jared7118/zero-btc-screen/presentation/screens/epd2in13v2.py", line 31, in _init_display
    epd.init(epd.FULL_UPDATE)
  File "/home/jared7118/.local/lib/python3.9/site-packages/waveshare_epd/epd2in13_V2.py", line 132, in init
    if (epdconfig.module_init() != 0):
  File "/home/jared7118/.local/lib/python3.9/site-packages/waveshare_epd/epdconfig.py", line 76, in module_init
    self.SPI.open(0, 0)
FileNotFoundError: [Errno 2] No such file or directory

Any ideas what is wrong? SPI is enabled (I've checked 2x)

Thanks in advance!!!!

**Comment by jared7118** [comment]
faulty screen
