### ISSUE TITLE
Can't start the app: NameError: name 'epd2in13_V2' is not defined

### ISSUE THREAD

**Issue by vinovod** [dr-mod/zero-btc-screen#41]
Still cannot figure out the issue

```
python3 ~/zero-btc-screen/main.py

Traceback (most recent call last):
  File "/home/pi/zero-btc-screen/main.py", line 60, in <module>
    main()
  File "/home/pi/zero-btc-screen/main.py", line 40, in main
    builder.bind(data_sink)
  File "/home/pi/zero-btc-screen/config/builder.py", line 23, in bind
    screen_class(observable=observable, **kwargs)
  File "/home/pi/zero-btc-screen/presentation/screens/epd2in13v2.py", line 23, in __init__
    self.epd = self._init_display()
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/zero-btc-screen/presentation/screens/epd2in13v2.py", line 30, in _init_display
    epd = epd2in13_V2.EPD()
          ^^^^^^^^^^^
NameError: name 'epd2in13_V2' is not defined. Did you mean: 'Epd2in13v2'?
```

I'm using Waveshare e-Ink v4 with Raspberry Pi Zero W and Raspberry OS Lite installed
Tried to modify config appropriately, but get undefined modules in any case.

Could you please dive into it? Thank you!

**Comment by onisuk** [comment]
yeah i get this exact same issue when following the guide, any updates?

**Comment by dr-mod** [comment]
Based on the error message, it seems the display drivers are not installed. Could you try running the following commands and let me know how it went?
```
git clone https://github.com/waveshare/e-Paper.git ~/e-Paper
pip3 install ~/e-Paper/RaspberryPi_JetsonNano/python/
```
